In [18]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
a.shape

(3, 2)

In [20]:
b = np.array([2,3,4])
b

array([2, 3, 4])

In [21]:
np.dot(b,a)

array([31, 40])

For a layer with more than one perceptron, the weights and inputs are no longer row vectors. Usefull trasnpose operations follow

In [22]:
print(b[:, None])

[[2]
 [3]
 [4]]


In [24]:
print(b.T)

[2 3 4]
